# Generated by Django 5.1.2 on 2025-11-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_users_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100, unique=True)),
                ('movie_date', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('budget', models.IntegerField()),
            ],
        ),
    ]
