# Generated by Django 5.1.2 on 2025-11-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='rating',
            field=models.CharField(max_length=10),
        ),
    ]
